CREATE TABLE Assunto (
    "Id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "Descricao" VARCHAR(255) NOT NULL,
    "Status" INTEGER NOT NULL
);


INSERT INTO Assunto ("Descricao", "Status") VALUES
('Introdução à Programação', 1),
('Estruturas de Dados e Algoritmos', 1),
('Banco de Dados Relacionais', 1),
('Desenvolvimento Web com Python', 1),
('Machine Learning Básico', 1),
('Redes de Computadores', 1),
('Introdução à Segurança da Informação', 1),
('Arquitetura de Software', 1),
('Metodologias Ágeis', 1),
('Fundamentos de Inteligência Artificial', 1);
